StudentsCommunity/Models/Enrollment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace StudentsCommunity.Models
{
    public class Enrollment
    {
        public int Id { get; set; }

        public int CoursesId { get; set; }

        public string StudentId { get; set; }

        public bool IsActive { get; set; } = true;

        [ForeignKey("StudentId")]
        public virtual ApplicationUser User { get; set; }
        [ForeignKey("CoursesId")]
        public virtual Courses Courses { get; set; }

    }
}

StudentsCommunity/Controllers/EnrollmentsController.cs
using Microsoft.AspNet.Identity;
using StudentsCommunity.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace StudentsCommunity.Controllers
{   [Authorize]
    public class EnrollmentsController : Controller
    {
        public ApplicationDbContext db = new ApplicationDbContext();



        [HttpGet]
        public ActionResult GetCourse()
        {
            ViewBag.CoursesId = new SelectList(db.Courses, "Id", "CourseName");
            return View();
        }

        [HttpPost]
        public ActionResult GetCourse(string CourseCode,int CoursesId)
        {
            Courses Course = db.Courses.Where(u => u.CourseCode.ToLower() == CourseCode.ToLower()&& u.Id == CoursesId)
                                 .FirstOrDefault();
            var UserId = User.Identity.GetUserId();
            List<Enrollment> MyCourses = db.Enrollment.Where(x => x.StudentId == UserId).ToList();
            bool IsCourseRegistered = false;
            foreach (var item in MyCourses)
            {
                if (item.Courses.CourseCode== CourseCode)
                {
                    IsCourseRegistered = true;
                }
            }

            var enrollment = new Enrollment();
            if (Course != null)
            {
               if (IsCourseRegistered == false)
                {
                        enrollment.StudentId = UserId;
                        enrollment.CoursesId = Course.Id;
                        db.Enrollment.Add(enrollment);
                        db.SaveChanges();
                        return RedirectToAction("Index", "Home");
                    
                }
                else
                {
                    ModelState.AddModelError("IsCourseRegistered", "you already Registered this Course");
                }
            }
            else
            {
                ModelState.AddModelError("CourseCode", "CourseCode Dosn't Exists");
            }

            ViewBag.CoursesId = new SelectList(db.Courses, "Id", "CourseName");
            return View();
        }

        public ActionResult MyCourses()
        {
            var UserId = User.Identity.GetUserId();
            var Enrollments = db.Enrollment.Where(a => a.StudentId == UserId);
            return View(Enrollments.ToList());
        }
        // GET: Enrollments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            //get enrollment Id
            int EnrollmentId = db.Enrollment.Where(x => x.CoursesId == id).FirstOrDefault().Id;

            Enrollment Enrollments = db.Enrollment.Find(EnrollmentId);
            if (Enrollments == null)
            {
                return HttpNotFound();
            }
            return View(Enrollments);
        }
        // GET: Enrollments/Create

        // GET: Enrollments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            int EnrollmentId = db.Enrollment.Where(x => x.CoursesId == id).FirstOrDefault().Id;

            Enrollment Enrollment = db.Enrollment.Find(EnrollmentId);
            if (Enrollment == null)
            {
                return HttpNotFound();
            }
            return View(Enrollment);
        }

        // POST: Enrollments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            int EnrollmentId = db.Enrollment.Where(x => x.CoursesId == id).FirstOrDefault().Id;

            Enrollment Enrollment = db.Enrollment.Find(EnrollmentId);
            db.Enrollment.Remove(Enrollment);
            db.SaveChanges();
            return RedirectToAction("MyCourses");
        }
    }
}

StudentsCommunity/Views/Enrollments/Delete.cshtml
@model StudentsCommunity.Models.Enrollment

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h3 class="alert-danger">Are you sure you want to delete this Course? <i class="fa fa-warning"></i></h3>
<div>
    <h4 class="note">Course Information</h4>

    <table class="table table-striped table-bordered table-inverse" style="width:100%">
        <tbody>

            <tr>
                <td>
                    @Html.DisplayNameFor(model => model.Courses.CourseName)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Courses.CourseName)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.DisplayNameFor(model => model.Courses.CourseCode)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Courses.CourseCode)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.DisplayNameFor(model => model.Courses.GroupNum)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Courses.GroupNum)
                </td>
            </tr>

        </tbody>
    </table>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
        </div>
    }
</div>

StudentsCommunity/Views/Enrollments/Details.cshtml
@model StudentsCommunity.Models.Enrollment

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div>
    <h4 class="note">Course Information</h4>

    <table class="table table-striped table-bordered table-inverse" style="width:100%">
        <tbody>


            <tr>
                <td>
                    @Html.DisplayNameFor(model => model.Courses.CourseName)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Courses.CourseName)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.DisplayNameFor(model => model.Courses.CourseCode)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Courses.CourseCode)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.DisplayNameFor(model => model.Courses.GroupNum)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Courses.GroupNum)
                </td>
            </tr>
        </tbody>
    </table>

        <div class="form-actions no-color">
            <a href="@Url.Action("MyCourses", "Courses")" class='btn btn-info btn-xs'>
                <i class="fa fa-arrow-left"></i>
                back
            </a>
            <a href="@Url.Action("Edit", "Courses", new { id = Model.Id } )" class='btn btn-success btn-xs'>
                <i class="fa fa-edit"> Edit</i>
            </a>
        </div>
  
</div>

StudentsCommunity/Views/Enrollments/GetCourse.cshtml
@model StudentsCommunity.Models.Enrollment

@{
    ViewBag.Title = "GetCourse";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



@using (Html.BeginForm("GetCourse", "Enrollments", FormMethod.Post))
{  
    <div class="form">
        <div class="note">
            <p>GetCourse</p>
        </div>
        <div class="form-content">
            @Html.ValidationMessage("IsCourseRegistered", new { @class = " text-danger" })
            @Html.ValidationMessage("CourseCode", new { @class = " text-danger" })
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                <div class="col-md-4">
                    @Html.DropDownList("CoursesId", (IEnumerable<SelectListItem>)ViewBag.CoursesId, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CoursesId, "", new { @class = "text-danger" })
                    <input type="text" class="form-control input-lg" name="CourseCode" placeholder="CourseCode" required = "required"/><br />
                </div>
                <input type="submit" class="btnSubmit" value="Register" />
            </div>
        </div>
    </div>

}

StudentsCommunity/Views/Enrollments/MyCourses.cshtml
@model IEnumerable<StudentsCommunity.Models.Enrollment>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="text-center">My Courses</h2>

<p>
    <a href="@Url.Action("GetCourse", "Enrollments")" class='b1'>
       Register New Course
    </a>
</p>
<table class="table table-striped table-bordered table-inverse" style="width:100%">
    <thead class="note">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Courses.CourseName)
            </th>
            <th>Manage</th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr class="text-center">
                <td>
                    @Html.DisplayFor(modelItem => item.Courses.CourseName)
                </td>
                <td class="text-center">
                    <a href="@Url.Action("Delete", "Enrollments", new { id = item.CoursesId } )" class='btn btn-danger btn-xs'>
                        <i class="fa fa-trash"></i>
                    </a>
                    @*<a href="@Url.Action("Details", "Enrollments", new { id = item.CoursesId } )" class='btn btn-info btn-xs'>
                        <i class="fa fa-info"></i>
                    </a>*@
                </td>
            </tr>
        }
    </tbody>
</table>