StudentsCommunity/Controllers/QuizzController.cs
using StudentsCommunity.Models;
using StudentsCommunity.viewModels;
using StudentsCommunity.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StudentsCommunity.Controllers
{
    public class QuizzController : Controller
    {
        public ApplicationDbContext db = new ApplicationDbContext();

        // GET: Quizz
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CreateQuiz(int? id)
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateQuiz(Quiz quiz, int id)
        {
            if (ModelState.IsValid)
            {
                quiz.CourseId = id;
                db.Quizs.Add(quiz);
                db.SaveChanges();
                return RedirectToAction("AddQuestions/" + quiz.QuizId);
            }
            return View();
        }

        public ActionResult AddQuestions(int? id)
        {
            // This is only for show by default one row for insert data to the database
            List<Question> ci = new List<Question> { new Question { QuestionId = 0, QuestionText = ""} };
            return View(ci);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddQuestions(List<Question> ci, int id)
        {
            if (ModelState.IsValid)
            {

                foreach (var i in ci)
                {
                    i.QuizId = id;
                    db.Questions.Add(i);
                }
                db.SaveChanges();
                ViewBag.Message = "Data successfully saved!";
                return RedirectToAction("AddChoices/" + id);
            }

            return View(ci);
        }

        public ActionResult AddChoices(int? id)
        {
            ViewBag.QuestionId = new SelectList(db.Questions.Where(x=>x.QuizId== id), "QuestionId", "QuestionText");

            // This is only for show by default one row for insert data to the database
            List<Choice> ci = new List<Choice> { new Choice { ChoiceId = 0, ChoiceText = "" } };
            return View(ci);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddChoices(List<Choice> ci,int QuestionId)
        {
            var Question = new Question();

            if (ModelState.IsValid)
            {

                foreach (var i in ci)
                {
                    i.QuestionId = QuestionId;
                    db.Choices.Add(i);
                }
                db.SaveChanges();
                ViewBag.Message = "Data successfully saved!";
                //return RedirectToAction("AddAnswers");
                }
            ViewBag.QuestionId = new SelectList(db.Questions, "QuestionId", "QuestionText");

            return View(ci);
        }

        public ActionResult AddAnswers(int? id)
        {
            ViewBag.QuestionId = new SelectList(db.Questions.Where(x=>x.QuizId==id), "QuestionId", "QuestionText");

            // This is only for show by default one row for insert data to the database
            List<Answer> ci = new List<Answer> { new Answer { AnswerId = 0, AnswerText = "" } };
            return View(ci);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddAnswers(List<Answer> ci, int QuestionId)
        {
            var Question = new Question();

            if (ModelState.IsValid)
            {

                foreach (var i in ci)
                {
                    i.QuestionId = QuestionId;
                    db.Answers.Add(i);
                }
                db.SaveChanges();
                ViewBag.Message = "Data successfully saved!";
                //return RedirectToAction("SelectQuizz");

            }
            ViewBag.QuestionId = new SelectList(db.Questions, "QuestionId", "QuestionText");

            return View(ci);
        }



        [HttpGet]
        public ActionResult SelectQuizz()
        {
            QuizVM quiz = new viewModels.QuizVM();
            quiz.ListOfQuizz = db.Quizs.Select(q => new SelectListItem
            {
                Text = q.QuizName,
                Value = q.QuizId.ToString()

            }).ToList();

            return View(quiz);
        }

        [HttpPost]
        public ActionResult SelectQuizz(QuizVM quiz)
        {
            QuizVM quizSelected = db.Quizs.Where(q => q.QuizId == quiz.QuizId).Select(q => new QuizVM
            {
                QuizId = q.QuizId,
                QuizName = q.QuizName,

            }).FirstOrDefault();

            if (quizSelected != null)
            {
                Session["SelectedQuiz"] = quizSelected;

                return RedirectToAction("QuizTest");
            }

            return View();
        }

        [HttpGet]
        public ActionResult QuizTest()
        {
            QuizVM quizSelected = Session["SelectedQuiz"] as QuizVM;
            IQueryable<QuestionVM> questions = null;

            if (quizSelected != null)
            {
                questions = db.Questions.Where(q => q.Quiz.QuizId == quizSelected.QuizId)
                   .Select(q => new QuestionVM
                   {
                       QuestionId = q.QuestionId,
                       QuestionText = q.QuestionText,
                       Choices = q.Choices.Select(c => new ChoiceVM
                       {
                           ChoiceId = c.ChoiceId,
                           ChoiceText = c.ChoiceText
                       }).ToList()

                   }).AsQueryable();


            }

            return View(questions);
        }

        [HttpPost]
        public ActionResult QuizTest(List<QuizAnswersVM> resultQuiz)
        {
            List<QuizAnswersVM> finalResultQuiz = new List<viewModels.QuizAnswersVM>();

            foreach (QuizAnswersVM answser in resultQuiz)
            {
                QuizAnswersVM result = db.Answers.Where(a => a.QuestionId == answser.QuestionId).Select(a => new QuizAnswersVM
                {
                    QuestionId = a.QuestionId,
                    AnswerQ = a.AnswerText,
                    isCorrect = (answser.AnswerQ.ToLower().Equals(a.AnswerText.ToLower()))

                }).FirstOrDefault();

                finalResultQuiz.Add(result);
            }

            return Json(new { result = finalResultQuiz }, JsonRequestBehavior.AllowGet);
        }


    }
}

StudentsCommunity/Views/Quizz/AddAnswers.cshtml
@model List<StudentsCommunity.Models.Answer>

@{
    ViewBag.Title = "Insert Bulk Data";
}
<style>
    td {
        padding: 5px;
    }
       input[type=text] {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}
</style>
<div style="width:700px; padding:35px; background-color:white;">
    @using (Html.BeginForm("AddAnswers", "Quizz", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        if (ViewBag.Message != null)
        {
            <div class="bg-success">
                @ViewBag.Message
            </div>
        }
        @Html.DropDownList("QuestionId", null, htmlAttributes: new { @class = "form-control chosen_a" });

        <div><a href="#" id="addNew" style="margin:8px" class="btn btn-primary">Add New Choice</a></div>
        <table id="dataTable" cellpadding="0" cellspacing="0" class="table">
            <thead class="bg-secondary">
                <tr>
                    <th class="text-primary">Answers</th>
                    <th></th>
                </tr>
            </thead>
            @if (Model != null && Model.Count > 0)
                {
                    int j = 0;
                    foreach (var i in Model)
                    {
                    <tr style="border:1px solid black">
                        <td>@Html.TextBoxFor(a => a[j].AnswerText, new { placeholder = "Write Answer ...", @class = "form-input" })</td>

                        <td>
                            @if (j > 0)
                            {
                                <a href="#" class="remove">Remove</a>
                            }
                        </td>
                    </tr>
                    j++;
                }
            }
        </table>
        <input type="submit" value="Save" class="btn btn-success" />
        <a href="@Url.Action("SelectQuizz", "Quizz")" class='btn btn-primary'>
            Try
        </a>
    }
</div>

@* Here I will add Jquery Code for validation / dynamically add new rows / Remove rows etc *@

@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
    <script language="javascript">

        $(document).ready(function () {

            //1. Add new row
            $("#addNew").click(function (e) {
                e.preventDefault();
                var $tableBody = $("#dataTable");
                var $trLast = $tableBody.find("tr:last");
                var $trNew = $trLast.clone();

                var suffix = $trNew.find(':input:first').attr('name').match(/\d+/);
                $trNew.find("td:last").html('<a href="#" class="remove">Remove</a>');
                $.each($trNew.find(':input'), function (i, val) {
                    // Replaced Name
                    var oldN = $(this).attr('name');
                    var newN = oldN.replace('[' + suffix + ']', '[' + (parseInt(suffix) + 1) + ']');
                    $(this).attr('name', newN);
                    //Replaced value
                    var type = $(this).attr('type');
                    if (type.toLowerCase() == "text") {
                        $(this).attr('value', '');
                    }

                    // If you have another Type then replace with default value
                    $(this).removeClass("input-validation-error");

                });
                $trLast.after($trNew);

                // Re-assign Validation
                var form = $("form")
                    .removeData("validator")
                    .removeData("unobtrusiveValidation");
                $.validator.unobtrusive.parse(form);
            });

            // 2. Remove
            $('a.remove').live("click", function (e) {
                e.preventDefault();
                $(this).parent().parent().remove();
            });

        });
    </script>
}

StudentsCommunity/Views/Quizz/AddChoices.cshtml
@model List<StudentsCommunity.Models.Choice>

@{
    ViewBag.Title = "Insert Bulk Data";
}
<style>
    td {
        padding: 5px;
    }
    input[type=text] {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}
</style>
@{var ID = Url.RequestContext.RouteData.Values["id"]; }
<div style="width:700px; padding:5px; background-color:white;">
    @using (Html.BeginForm("AddChoices", "Quizz", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        if (ViewBag.Message != null)
        {
            <div style="border:solid 1px green">
                @ViewBag.Message
            </div>
        }
        @*@Html.DropDownListFor(model => model.QuestionId, ViewBag.QuestionList as SelectList, "--select--", new { @class = "form-control" })*@
        @Html.DropDownList("QuestionId", null, htmlAttributes: new { @class = "form-control chosen_a" });

        <div><a href="#" id="addNew" style="margin:8px" class="btn btn-primary">Add New Choice</a></div>
        <table id="dataTable" cellpadding="0" cellspacing="0" class="table">
            <thead class="bg-secondary">
                <tr>
                    <th class="text-primary">Choices</th>
                    <th></th>
                </tr>
            </thead>
                @if (Model != null && Model.Count > 0)
                {
                    int j = 0;
                    foreach (var i in Model)
                    {
                        <tr style="border:1px solid black">
                            <td>@Html.TextBoxFor(a => a[j].ChoiceText ,new { placeholder = "Write Choice ...", @class = "form-input" })</td>

                            <td>
                                @if (j > 0)
                                {
                                    <a href="#" class="remove">Remove</a>
                                }
                            </td>
                        </tr>
                        j++;
                    }
                }
</table>
        <input type="submit" value="Save" class="btn btn-success" />
        <a href="@Url.Action("AddAnswers", "Quizz",new{ id = ID })" class='btn btn-primary'>
            Add Answers
        </a>


    }
</div>

@* Here I will add Jquery Code for validation / dynamically add new rows / Remove rows etc *@

@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
    <script language="javascript">

        $(document).ready(function () {

            //1. Add new row
            $("#addNew").click(function (e) {
                e.preventDefault();
                var $tableBody = $("#dataTable");
                var $trLast = $tableBody.find("tr:last");
                var $trNew = $trLast.clone();

                var suffix = $trNew.find(':input:first').attr('name').match(/\d+/);
                $trNew.find("td:last").html('<a href="#" class="remove">Remove</a>');
                $.each($trNew.find(':input'), function (i, val) {
                    // Replaced Name
                    var oldN = $(this).attr('name');
                    var newN = oldN.replace('[' + suffix + ']', '[' + (parseInt(suffix) + 1) + ']');
                    $(this).attr('name', newN);
                    //Replaced value
                    var type = $(this).attr('type');
                    if (type.toLowerCase() == "text") {
                        $(this).attr('value', '');
                    }

                    // If you have another Type then replace with default value
                    $(this).removeClass("input-validation-error");

                });
                $trLast.after($trNew);

                // Re-assign Validation
                var form = $("form")
                    .removeData("validator")
                    .removeData("unobtrusiveValidation");
                $.validator.unobtrusive.parse(form);
            });

            // 2. Remove
            $('a.remove').live("click", function (e) {
                e.preventDefault();
                $(this).parent().parent().remove();
            });

        });
    </script>
}

StudentsCommunity/Views/Quizz/AddQuestions.cshtml
@model List<StudentsCommunity.Models.Question>
@{
    ViewBag.Title = "Insert Bulk Data";
}
<style>
    td {
        padding: 5px;
    }
   input[type=text] {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}
</style>
<div style="width:700px; padding:5px; background-color:white;">
    @using (Html.BeginForm("AddQuestions", "Quizz", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        if (ViewBag.Message != null)
        {
            <div style="border:solid 1px green">
                @ViewBag.Message
            </div>
        }

        <div><a href="#" id="addNew" class="btn btn-primary" style="margin:8px">Add New Question</a></div>
        <table id="dataTable" border="0" cellpadding="0" cellspacing="0" class="table">
            <tr class="bg-secondary">
                <th>QuestionText</th>
                <th></th>
            </tr>
            @if (Model != null && Model.Count > 0)
            {
                int j = 0;
                foreach (var i in Model)
                {
                    <tr style="border:1px solid black">
                        <td>@Html.TextBoxFor(a => a[j].QuestionText, new { placeholder = "Write New Question ...", @class = "form-input" })</td>
                        <td>
                            @if (j > 0)
                            {
                                <a href="#" class="remove">Remove</a>
                            }
                        </td>
                    </tr>
                    j++;
                }
            }
        </table>
        <input type="submit" value="Save" class="btn btn-success"/>
    }
</div>

@* Here I will add Jquery Code for validation / dynamically add new rows / Remove rows etc *@

@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
    <script language="javascript">
        $(document).ready(function () {

            //1. Add new row
            $("#addNew").click(function (e) {
                e.preventDefault();
                var $tableBody = $("#dataTable");
                var $trLast = $tableBody.find("tr:last");
                var $trNew = $trLast.clone();

                var suffix = $trNew.find(':input:first').attr('name').match(/\d+/);
                $trNew.find("td:last").html('<a href="#" class="remove">Remove</a>');
                $.each($trNew.find(':input'), function (i, val) {
                    // Replaced Name
                    var oldN = $(this).attr('name');
                    var newN = oldN.replace('[' + suffix + ']', '[' + (parseInt(suffix) + 1) + ']');
                    $(this).attr('name', newN);
                    //Replaced value
                    var type = $(this).attr('type');
                    if (type.toLowerCase() == "text") {
                        $(this).attr('value', '');
                    }

                    // If you have another Type then replace with default value
                    $(this).removeClass("input-validation-error");

                });
                $trLast.after($trNew);

                // Re-assign Validation
                var form = $("form")
                    .removeData("validator")
                    .removeData("unobtrusiveValidation");
                $.validator.unobtrusive.parse(form);
            });

            // 2. Remove
            $('a.remove').live("click", function (e) {
                e.preventDefault();
                $(this).parent().parent().remove();
            });

        });
    </script>
}

StudentsCommunity/Views/Quizz/CreateQuiz.cshtml
@model StudentsCommunity.Models.Quiz

@{
    ViewBag.Title = "CreateQuiz";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>CreateQuiz</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.QuizName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QuizName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QuizName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Start" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

StudentsCommunity/Views/Quizz/QuizTest.cshtml
@model IQueryable<StudentsCommunity.viewModels.QuestionVM>

@{
    int count = 1, countR = 0;
}


@if (Model != null && Model.Any())
{

    foreach (var question in Model)
    {
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h3>
                        <span class="badge badge-warning">@string.Format("{0}{1}.", "Q", count)</span>
                        <span id="@string.Format("{0}{1}", "ID_Q", count)" style="display:none;">@question.QuestionId</span>
                        <p style="display: inline;" id="@string.Format("{0}{1}", "Q", count)">@question.QuestionText</p>
                    </h3>
                </div>

                <div class="quiz" id="quiz" data-toggle="buttons">

                    @foreach (var choice in question.Choices)
                    {
                <label class="element-animation1 btn btn-lg btn-primary btn-block">
                    <span class="btn-label justify-content-center"><i class="fa fa-angle-right"></i></span>
                    <input type="radio" name="@string.Format("{0}{1}", "inlineRadioOptions",count)" id="@string.Format("{0}{1}", "inlineRadio", countR)" value="@choice.ChoiceText" style="margin-left: -16px;"> @choice.ChoiceText
                </label><br />
                        countR++;
                    }

                </div> <!--END Choices-->

                <div class="modal-footer text-muted">
                    <div id="@string.Format("{0}{1}{2}", "Ans","Q", count)">


                    </div>
                </div>

            </div>
        </div>
                <!-- END BlockQ -->
        count++;
    }

                <div class="text-center">
                    <span id="countQuections" style="display:none;">@count</span>
                    <button type="button" id="SubmitQuiz" class="btn btn-primary" style="margin-top: 10px;"><span class="glyphicon glyphicon-ok"></span>   Submit Quiz </button>

                </div>
}



@section Scripts
{
    <script type="text/javascript">

        $(document).ready(function () {

            $('#SubmitQuiz').on('click', function () {

                //count Questions
                var sel = $('#countQuections').text();

                console.log(sel);

                var resultQuiz = [], countQuestion = parseInt(sel), question = {}, j = 1;

                for (var i = 1; i < countQuestion; i++) {
                    question = {
                        QuestionID: $('#ID_Q' + i).text(),
                        QuestionText: $('#Q' + i).text(),
                        AnswerQ: $('input[name=inlineRadioOptions' + i + ']:checked').val()
                    }

                    resultQuiz.push(question);
                }

                $.ajax({

                    type: 'POST',
                    url: '@Url.Action("QuizTest", "Quizz")',
                    data: { resultQuiz },

                    success: function (response) {

                        if (response.result.length > 0) {
                            for (var i = 0; i < response.result.length; i++) {
                                if (response.result[i].isCorrect == true) {

                                    $('#AnsQ' + j).html('<div class="alert alert-success" role="alert"><span class="fa fa-thumbs-up" aria-hidden="true"></span> Correct answer</div>');
                                }
                                else {
                                    $('#AnsQ' + j).html('<div class="alert alert-danger" role="alert"> <span class="fa fa-thumbs-down" aria-hidden="true"></span> Incorrect answer - The Good Answer is <b>' + response.result[i].AnswerQ + '</b></div>');
                                }
                                j++;
                            }
                        }
                        else {
                            alert("Something Wrong");
                        }


                        //console.log(response.result.length);

                    },
                    error: function (response) {

                    }
                });

                console.log(resultQuiz);

            });



        });

    </script>
}

StudentsCommunity/Views/Quizz/SelectQuizz.cshtml
@model StudentsCommunity.viewModels.QuizVM

@{
    ViewBag.Title = "SelectQuizz";
}

<div class="container">



    <div class="SelQuiz">

        <div class="panel panel-default" style="width: 37%; margin: 20% 32%;">
            <div class="panel-heading">Select Your Quiz</div>
            <div class="panel-body">

                @using (Html.BeginForm("SelectQuizz", "Quizz", FormMethod.Post))
                {
                    @Html.DropDownListFor(model => model.QuizId, Model.ListOfQuizz, new { @class = "form-control" } )<br/>
                    <button type="submit" id="Enter" class="btn btn-success btn-lg" style="width:100%;"><span class="glyphicon glyphicon-ok"></span>   Let's GO </button>
                }

            </div>
        </div>

    </div>

</div>  <!-- END CONTAINER -->