StudentsCommunity/Models/PersonalInformation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace StudentsCommunity.Models
{
    public class PersonalInformation
    {
        [Key, ForeignKey("User")]
        public string UserId { get; set; }

        public string FullName { get; set; }
        public int StudentId { get; set; }
        public string UserImage { get; set; }
        public string Skills { get; set; }

        public virtual ApplicationUser User { get; set; }

    }
}

StudentsCommunity/Controllers/PersonalInformationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StudentsCommunity.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.IO;

namespace StudentsCommunity.Controllers
{  [Authorize]
    public class PersonalInformationsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: PersonalInformations
        public ActionResult Index()
        {
            var currentUserId = User.Identity.GetUserId();

            // Look up existing record
            var personalInformation = db.PersonalInformations
                                                .FirstOrDefault(p => p.UserId == currentUserId);
            return View(personalInformation);
        }
        
        // GET: PersonalInformations/Create
        public ActionResult AddOrEdit()
        {
            var currentUserId = User.Identity.GetUserId();
            var PersonalInformation = db.PersonalInformations.Where(x => x.UserId == currentUserId).FirstOrDefault<PersonalInformation>();
            if (PersonalInformation == null)
            {
                return View(new PersonalInformation());
            }
            else
                return View(PersonalInformation);
        }

        // POST: PersonalInformations/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddOrEdit(PersonalInformation personalInformation, HttpPostedFileBase upload)
        {
            var currentUserId = User.Identity.GetUserId();
            personalInformation.UserId = currentUserId;
            var currentInformation = db.PersonalInformations.Where(x => x.UserId == currentUserId).FirstOrDefault<PersonalInformation>();
            var CurrentUser = db.Users.Where(a => a.Id == currentUserId).SingleOrDefault();

            if (currentInformation == null)
            {
                //make upload optional 
                if (upload != null)
                {
                string path = Path.Combine(Server.MapPath("~/Uploads"), upload.FileName);
                upload.SaveAs(path);
                personalInformation.UserImage = upload.FileName;
                }

                db.PersonalInformations.Add(personalInformation);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                
                string oldPath = Path.Combine(Server.MapPath("~/Uploads"), personalInformation.UserImage);

                if (upload != null)
                {   //leave defult image
                    if (personalInformation.UserImage != "img.png")
                    {
                        System.IO.File.Delete(oldPath);
                    }

                    string path = Path.Combine(Server.MapPath("~/Uploads"), DateTime.Now.ToString("_yyyy_MM_dd_HH_mm_ss")+ upload.FileName);
                    upload.SaveAs(path);
                personalInformation.UserImage = DateTime.Now.ToString("_yyyy_MM_dd_HH_mm_ss") + upload.FileName;
            }


            // Update user
            var store = new UserStore<ApplicationUser>(db);
                var manager = new ApplicationUserManager(store);
                var user = manager.Users.FirstOrDefault(u => u.Id == currentUserId);
                user.PersonalInformation.FullName = personalInformation.FullName;
                user.PersonalInformation.StudentId =personalInformation.StudentId ;
                user.PersonalInformation.UserImage = personalInformation.UserImage;
                user.PersonalInformation.Skills = personalInformation.Skills;
                manager.Update(user);
                return RedirectToAction("Index");
            }
            
        }

        
    }
}

StudentsCommunity/Views/PersonalInformations/AddOrEdit.cshtml
@model StudentsCommunity.Models.PersonalInformation

@{
    ViewBag.Title = "Edit Profile";
}

@using (Html.BeginForm("AddOrEdit", "PersonalInformations", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="alert alert-danger" id="error-div" style="display:none">
        <span id="view-err">
        </span>
    </div>
<div class="row">

    <div class="col-sm-3">
        <!--left col-->


        <div class="text-center">

                <img src="~/Uploads/@Html.DisplayFor(model=> model.UserImage)"
                     class="rounded-circle thumbnail" />
                <h6>Upload a different photo...</h6>
            <!-- File Button -->
            <div class="input-group">
                <input type="file" name="upload" id="myImage" style="display:none">
                <input type="text" id="fake-file-input-name" disabled="disabled" placeholder="Select photo" class="form-control">
                <span class="input-group-btn">
                    <button id="fake-file-button-browse" type="button" class="btn btn-default">
                        <span class="fa fa-photo"></span>
                    </button>
                </span>
            </div>

                @Html.ValidationMessageFor(model => model.UserImage, "", new { @class = "text-danger" })
            </div>


    </div><!--/col-3-->
    <div class="col-sm-9">

        <div class="card">
            <div class="card-header">Edit profile</div>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            @Html.HiddenFor(model => model.UserId)
            @Html.HiddenFor(model => model.UserImage)
            <div class="card-body" id="home">
                <hr>
                    <div class="form-group">

                        <div class="col-xs-6">
                            <label for="first_name"><h4>FullName</h4></label>
                            @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">

                        <div class="col-xs-6">
                            <label for="last_name"><h4>StudentId</h4></label>
                            @Html.EditorFor(model => model.StudentId, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.StudentId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                <div class="form-group">

                    <div class="col-xs-6">
                        <label for="last_name"><h4>Skills</h4></label>
                        @Html.EditorFor(model => model.Skills, new { htmlAttributes = new { @class = "form-control", id = "skill" } })
                        @Html.ValidationMessageFor(model => model.Skills, "", new { @class = "text-danger" })
                    </div>
                </div>

                    <div class="form-group">
                        <div class="col-xs-12">
                            <br>
                            <input type="submit" value="Save" class="btn btn-lg btn-success" id="save" />

                          </div>
                    </div>

                <hr>

            </div>

        </div>
    </div>

</div>

}

@section scripts{
    <script>
        //Autocomplete with tokenfield
        $('#skill').tokenfield({
            autocomplete: {
                source: ['PHP', 'HTML', 'JQuery', 'Javascript', 'CSS', 'Laravel', 'CakePHP', 'Asp.net', 'C#', 'Sql', 'FuelPHP', 'PHPixie', 'Mysql'],
                delay: 100
            },
            showAutocompleteOnFocus: true
        });
        $(function () {

                $("#save").click(function () {

                      //Check if the input is Empty
                    //if ($("#myImage").val() == "") {
                    //      $("#error-div").fadeIn();
                    //      $("#view-err").append("please select right extention");
                    //      return false;
                    //  }

                    if ($("#myImage").val() != "") {
                        //Check if the Image extension is valid
                        var filename = document.getElementById("myImage").value;
                        var extensionImg = filename.substr(filename.lastIndexOf('.') + 1);
                        var validExtensions = ['jpg', 'png', 'gif', 'bmp'];
                        if ($.inArray(extensionImg, validExtensions) == -1) {
                            $("#error-div").fadeIn();
                            $("#view-err").append("please select right extention");
                            return false;
                        }

                        //Check if the Image Size is valid (2 mb)
                        var myFileSize = document.getElementById("myImage").files[0].size / 1024 / 1024;

                        if (myFileSize > 2) {
                            $("#error-div").fadeIn();
                            $("#view-err").append("size is larger than 2Mb");
                            return false;
                        }
                    }
                });
            //File Button
                document.getElementById('fake-file-button-browse').addEventListener('click', function () {
                    document.getElementById('myImage').click();
                });

                document.getElementById('myImage').addEventListener('change', function () {
                    document.getElementById('fake-file-input-name').value = this.value;

                    document.getElementById('fake-file-button-upload').removeAttribute('disabled');
                });
        });
    </script>
}

StudentsCommunity/Views/PersonalInformations/Index.cshtml
@using StudentsCommunity.Models;
@using Microsoft.AspNet.Identity
@using Microsoft.AspNet.Identity.EntityFramework;
@{
    ViewBag.Title = "Profile";
}

@{
    var manager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));

    var currentUser = manager.FindById(User.Identity.GetUserId());

<div class="container main-secction">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12 image-section">
            <img src="~/img/PB.jpg">
        </div>

        <div class="row user-left-part">
            <div class="col-md-3 col-sm-3 col-xs-12 user-profil-part pull-left">
                <div class="row ">
                    <div class="col-md-12 col-md-12-sm-12 col-xs-12 user-image text-center">
                        <img src="~/Uploads/@currentUser.PersonalInformation.UserImage" class="rounded-circle">
                    </div>
                    <div class="col-md-12 col-sm-12 col-xs-12 user-detail-section1 text-center">
                        <button class="btn btn-success btn-block follow" id="addClass" type="button">Contact me  <span class="fa fa-comment"></span></button>
                    </div>
                    <div class="row user-detail-row">
                        <div class="col-md-12 col-sm-12 user-detail-section2 pull-left">
                            <h4>info</h4><div class="border"></div>
                            <div class="row">
                                <div class="col-md-4">
                                    <label>User Name</label>
                                </div>
                                <div class="col-md-6">
                                    <p>@currentUser.UserName</p>
                                </div>
                            </div>
                             <div class="row">
                                <div class="col-md-4">
                                    <label>ID</label>
                                </div>
                                <div class="col-md-6">
                                    <p>@currentUser.PersonalInformation.StudentId</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4">
                                    <label>Name</label>
                                </div>
                                <div class="col-md-6">
                                    <p>@currentUser.PersonalInformation.FullName</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4">
                                    <label>Email</label>
                                </div>
                                <div class="col-md-6">

                                    <p>@currentUser.Email</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4">
                                    <label>Phone</label>
                                </div>
                                <div class="col-md-6">
                                    <p>@currentUser.PhoneNumber</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4">
                                    <label>Skills</label>
                                </div>
                                <div class="col-md-6">
                                    <p>@currentUser.PersonalInformation.Skills</p>
                                 </div>
                            </div>
                            <a href="@Url.Action("AddOrEdit","PersonalInformations")" class="btn btn-primary">Edit</a>
                            <hr/>
                            <a href="@Url.Action("EditProfile","Account")" class="btn btn-primary">change password</a>


                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-9 col-sm-9 col-xs-12 pull-right profile-right-section">
                <div class="row profile-right-section-row">
                    <div class="col-md-12 profile-header">
                        <div class="row">
                            <div class="col-md-8 col-sm-6 col-xs-6 profile-header-section1 pull-left">
                                <h1>My Courses</h1>
                            </div>
                            <div class="col-md-4 col-sm-6 col-xs-6 profile-header-section1 text-right pull-rigth">
                                @if (User.IsInRole("Students"))
                                {    <a class="btn btn-primary btn-block" href="@Url.Action("MyCourses","Enrollments")">Manage courses</a>

                                }
                                @if (User.IsInRole("Instructors"))

                                {    <a class="btn btn-primary btn-block" href="@Url.Action("MyCourses","Courses")">Manage courses</a>

                                }
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="row">
                            @{var list = (List<Courses>)Session["Courses"];
                            }
                            @foreach (var Course in list)
                            {      <div class="col-md-8">
                                <a href="@Url.Action("Details", "Courses", new { id = Course.Id } )">
                                    <div class="notice notice-lg notice-info">
                                        <strong>@Course.CourseName</strong>
                                    </div>
                                </a>
                            </div>

                            }

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
}

<script src="~/Scripts/jquery-3.0.0.min.js"></script>

@section scripts{
    <script>
        $(document).ready(function () {
            $(function () {

                var s = "@currentUser.PersonalInformation.Skills";
                var match = s.split(', ')
                console.log(match)
                for (var a in match) {
                    var variable = match[a]
                    console.log(variable)
                }
            })

            $("#addClass").click(function () {
                $('#qnimate').addClass('popup-box-on');
            });

            $("#removeClass").click(function () {
                $('#qnimate').removeClass('popup-box-on');
            });
        });
    </script>
}